#!/usr/bin/env bash
# Setting up server to curl port 80 with no issues
apt-get update
apt-get -y install curl
rm /etc/nginx/sites-available/default
rm /etc/nginx/sites-enabled/default
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
